### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by ASKemp** [fingers10/JqueryDataTables#2]
Many thanks for this but when running I just get an empty, one row table. I suspect I'm missing something?

**Comment by fingers10** [comment]
Hey ASKemp,

Did you get any error logged in browser console? Are you getting rows from database in server side?
Can you share a link to your code repo?

Thanks,
Abdul

**Comment by ASKemp** [comment]
Hi, thanks for the reply.
I edited the app.js to remove the old, commented out code and also removed the.

"use strict";

$(() => {
    if ($('#fingers10').length !== 0) { 

...

 }
});

wrapped around it. Works then.

**Comment by ASKemp** [comment]
It's the 
$(() => {  ... }); 
that is causing the js not to run on my setup

**Comment by fingers10** [comment]
Glad you resolved yourself. There is nothing wrong with the above code. The code you commented says that on document ready look for a table with `id=fingers10` and if a match is found then the jQuery datatable code inside the blocks will run.

Cheers,
Abdul

**Comment by fingers10** [comment]
Which browser are you using? This is arrow syntax and will work only on
modern browsers that supports es6 syntax.

Cheers,
Abdul

**Comment by ASKemp** [comment]
Many thanks, yes, but wasn't working on mine for some reason.
