### ISSUE TITLE
Searching for mobile number in DataTable gives exception "Invalid Search Value".

### ISSUE THREAD

**Issue by mayank1991mishra** [fingers10/JqueryDataTables#4]
I have implemented this datatbles in my project in asp.net core 3.0 project. My view model is almost same as my database model except a fiew fields which I have mapped with automapper.
Everything i.e create, edit and delete works fine but when I search for mobile number then it gives exception. Searching on other fields works fine. My mobile is declared as string in both models and name of property is also same.

**Comment by fingers10** [comment]
Can you share you view model and entity? Did you check the demo solution? Demo solution works fine.

**Comment by mayank1991mishra** [comment]
Just create a simple database model with mobile as a string and a view model with mobile as a string. After that seed it and use that in memory object for datatable. then search in that mobile field in datatble it will throw exception. Your demo works fine because in that salary is declared as nullable long but in my case my mobile no is not a numeric field.

My view model

`public class PassengerViewModel
    {
        public int Id { get; set; }
        public decimal PrimaryId { get; set; }

        [SearchableString(EntityProperty = "CustomerId")]
        [Sortable(EntityProperty = "CustomerId")]
        public string Customer { get; set; }

        [SearchableString(EntityProperty = "GuestName")]
        [Sortable(EntityProperty = "GuestName")]
        public string Name { get; set; }

        [SearchableInt(EntityProperty = "Mobile")]
        [Sortable(EntityProperty = "Mobile")]
        public string Mobile { get; set; }

        [SearchableString(EntityProperty = "Email")]
        [Sortable(EntityProperty = "Email")]
        public string Email { get; set; }

        public string Action { get; set; }
    }`

and my model : 
`public class MasterPassenger
    {
        public int Id { get; set; }
        public decimal PrimaryId { get; set; }
        public string CustomerId { get; set; }
        public string GuestName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
    }`

**Comment by mayank1991mishra** [comment]
I made some changes in your demo code and it seems to work fine. But with database implementation something seems to break the functionality for mobile searching.
I am closing it for now but I will keep testing and will comment here if I find something.

**Comment by fingers10** [comment]
Change the `[SearchableInt(EntityProperty = "Mobile")]` to `[SearchableString(EntityProperty = "Mobile")]` for `Mobile` property in `PassengerViewModel`
