### ISSUE TITLE
Demo fails on DateTime search.

### ISSUE THREAD

**Issue by dbychkov** [fingers10/JqueryDataTables#5]
Run demo project.
Try to search for 2012 in Start Date column.
See error message "DataTables warning: table id=fingers10 - Internal Server Error"
"Loading Data" spinner gets stuck forever.

**Comment by fingers10** [comment]
Hi @dbychkov ,

You need to search the full date. Not the year part alone. Please try searching the full date.

Thanks,
Abdul Rahman

**Comment by dbychkov** [comment]
Yes, I understand that but it crashes the whole thing if the user types
part of the date and table becomes unusable, it becomes stuck in the
loading data phase. The same thing happens if I try to search for text data
in a numerical column.

===
Thanks.
Dmitriy Bychkov

**Comment by fingers10** [comment]
sorry for the delayed response. Jquery DataTables have a regex option for searching. Does that help you in any ways? or restricting the user inputs with regex in onkeypress event in search inputs would help?

Thanks,
Abdul Rahman

**Comment by fingers10** [comment]
I'm closing this as I don't get any response.
