### ISSUE TITLE
Error when multiple columns are being searched

### ISSUE THREAD

**Issue by vbharuwa** [fingers10/JqueryDataTables#7]
Please try with making a change in app.js

 $('#btnExternalSearch').click(function () {
            table.columns(([0, 1, 2, 4])).search($('#txtExternalSearch').val()).draw();
        });

You will get an error 
at EnumSearchExpressionProvider with "Invalid Search value".

Can you please allow for a search on enums if search value does not match the enum values. 
It shall return no data

**Comment by fingers10** [comment]
yes right now if the library cannot parse the enum value it will throw error. I'll look on this in the upcoming release. Mean while please post the issue in [JqueryDataTablesServerSide](https://github.com/fingers10/JqueryDataTablesServerSide/issues)

**Comment by fingers10** [comment]
I tried this approach. EF Core doesn't allow this by default. I cannot use contains on `enum` property in dbset. Here is the error

> The LINQ expression 'DbSet<DemoEntity>
>     .Where(d => d.Position.ToString().Contains("acc"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

**Comment by fingers10** [comment]
@vbharuwa I figured out an workaround after getting in touch with the EFCore Team. This issue will be fixed in the upcoming release. You can now perform a contains search in `enum` properties.

**Comment by fingers10** [comment]
This is now fixed and released in `v4.0.0`
