### ISSUE TITLE
"JqScripts" - not working in IE11! 

### ISSUE THREAD

**Issue by LisnyakTaras** [fingers10/JqueryDataTables#8]
![screenshot2](https://user-images.githubusercontent.com/18196502/79702078-b3c05900-82aa-11ea-8cce-dcba3aa54ad3.PNG)

![Снимок](https://user-images.githubusercontent.com/18196502/79702066-9ee3c580-82aa-11ea-9865-136d9b89860b.PNG)
In runtime i have empty table!

**Comment by fingers10** [comment]
@LisnyakTaras did you try this in chrome?

**Comment by fingers10** [comment]
This is not the problem with the scripts/project. IE 11 doesn't support arrow functions. Please read [this stackoverflow question](https://stackoverflow.com/questions/40216015/why-doesnt-this-arrow-function-work-in-ie-11) for further analysis.

**Comment by LisnyakTaras** [comment]
wwwroot\js\app.js  - translated to ES5

[Bable](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=EQVwzgpgBGAuBOBLAxrYBuAUJgJACjwEooBeAPigG9MpapEAzKPfAcgGIHEA7AcwnhgAjAAZWhAHQAbCH1gALKAEISJKCOLUadHQDcAhvCix9AIxmkobTj36DR4iQBF9JgCpmZeajt90p-nwg-vwAXFTaflFQAA7wAPbIEGBgtuHAADLx-gAmtlAuJhLFwAA0kdG-AF4C8QBKEMjx8Dlg6QBy8VAAtq7I8vnwjc2tUAzxINw5wBXRAL7llXRxicmpfOEIIBCLSzACugIAyog5EJvw27tLIwIAwhBSUmBu8TEXV7NR-iCw8QDqpwUHx2Xz8ZwYAgaUwEIOulRkcnkAFlZCBwgBtDEAVlKUFEeKEuKgACYRHiALRCAC6eJxhPJ-OJZLxwAAgk9gNTaWDfDl4t1wqwADzABIAd2AoqaUgpYG6VJJUBlFO6OQpADZgAAhMjS-Ky-WK5UG1XqjXGCAAD1gFKQvHkaCkZD1Yvikv1hoVQhJwAQLtFEqlwBVRp9Jtlaop2OAiFdoe9SpVUYA7MAYi7WPDoqZfn9uG0oBjedEfHtorBrbAhQBRK0xZqwYxdOtJKRZkt7ZABFLtfTdc5QVimWDcKAj7hy7rj0cUnKGADWHfL0X0qEQ8W44QYk3Xm-YOygOVgeO48TOeKa3C4vE0nZXUHFPH54ukiVcG-4EnkQyYamAAD0AASAoQABADiECwK2jwYPelQLPB0Q8Ig1ZjLusCfsw-gxIgp7noeV43neD5LPgZ5nJIQzdPEhx3D2YB4Kwx4UrmsD5uIWCkb4cxIXQiHcWW3G0JWNpCncQyuBAy7CbQ3b6L2_aDsOo4zpO8pqXKIDIEkKQybJa6YZu24YVheCHse-EXia16ILeESyX41jIJJlbIue-jtpINHzlITFgPI7qcXxfgCY5KFoTu3B7mOeA4XhUAUYRm7EQ5jk6ORBFURANF0QxTEsWxHGEFxjm8dx5V7Dy5b6AAVvoVrhEJK6wAAnjEg7AAACgA8kcbhlCFUAgPAUhCsBoEAVkuQeOYYH6SuV6VtwsBuO1nU4TEUgoB-m4AbVYCbugyryIYkCwCQvwMBSAAcg3cQprXRXCQ3yBAuQCIWzXccAAAaRx1AAYhSbg9QA0jW7TAOE_LICAA4rRIACO2zwK1RyPI0fzwExGLcEpJDAAA-kTDQo8ksAAGoCIwO1GdwrwLrIXKOAYUjbENYUPvOJgmdF9PMDz-gkY5MhNrkeT055lOedsYCWBi1KlQZOSS5-0uy8kGIiNSljsqrqHq1IUBdYYSmVoI-JwelEuG5uGvs1rNJ62yBtS8bpvwObn2ktbjlCxIrtq_bUgy478tqLb7th3LWBDToQywCNY4AFJHD17QSHASB8IwrV4ELJWc_BXOVDK8MFpiQ3faRQvpAAktM2akfjA7pBASP3Y5uiIKkc3bp5kDNw-kCGP0niDgwg-gultxe_3YzT5zw-VDX3OuPoHRKV3smt51TQzBVK-lvHdB11A3XxKk9M78Je_t53y_V6ftDn8APUMFwum39x98Xx3h9SKl3LGvFcb8nA5XiO0CmEAcgZAgIcKQPVuAQAkHWDqSBZBJB_i3JSD9AEPmAXsUB5ZwGQOgXAWB8DEHINQXWZaqRNw4IfH_YAACn6CRfkeDe6QIE0QoZWOBCDHi0OcOQmBQjEFuHFFfCQRwTDwFgIUZIzCVxDBhPAPmMVBYbzxG1DqeIJQi3SrQRgOiTCEC4dEROydHzPndBIGiCNYAFw3pIcY8BeguOAE4JwAFkTIgAgATRCUE4ARcTF0EeJAKxUQbHwDHNwEATxlbCSISwvBF9eBoA4aREhewyH8IkdQkRKCxFFMoZIx40jZFHE8oYVqqjyysKkJWAhK50mry4XPCeA9ngz0ck-Y88hwiiHJFwwpUDinCKQWUvhUzKklKkDUsAgcYpNL2Oos4mj0L8zMkLPR61DHumMSY-JY4AAGwo8i6DILEh8woir7n0RAQmTzuDAGVAxN5qkJxTk0jwcYPR4AUiVBOGsktPlCwpEzVqhMcCUAlBIRucxgBkAhahYUAF3l3MiQ895xh1pvLzEwr5CkwA_LHH8jSfz5x8AEGpCBYsIBQo3jCiAcLgAIqRSitFTKoIQCxTi-5lQsU3LIBc1JFVi7lmpLyOYRdeQmDmhIcu3QCxEAkMItGeAoraLwM-a0pzojWC4PS-wIhjBvVyMYTRPYmzAg7kxKAABqegMIrSuqHMQHgMRfjiCGhITcTFYUgBiAtbieqBbmWNeFJg5kJCwruARUgqh8QAGZY2ROVTIVVBoK4sDwAoXukgYiGFkC4yQhqrREC9awUIPc-4yEcKPeA_Qi0DFWWzbYkgche3FEQKVZUuEKqHbQUd2ATUF0SPDCtljyxBs_kxbsKAlx4g4BOCS71KwBoXcG1gK7kBrqHOwTdrlpJ4ijWZLNlRISwHbawCaA4AJbqkgBCNeSRUDgUOeIUvV-oftksgNcb0hRngpMB_oF6RWmHPK1cIKDxRQAAKp1AyBjMe8hPb9kYohqAgNmjdEKPoadcNnHI1RujTGqBmhMU4J419O7CDMZHfOxyEgFCyAIEMMADYCwQGIOQNK2aJ4SDqg1CQQwpDZByIOkVzlz3uV8o4HynkmIDDOMFPFR4Z3kfJmjDGMgaM4w4AwBj57HA8agnJ9KCquGqr6PIAgAgEjwEExQfJD4ryHVzdJ3g5l4CuYiWVYLSwJ28nwLDWdK02NLEXQwZd20j1ZiHBIcFktd17CDdwRLq6UusDS6ODFsAUtXv3LWzzvhvNNlOJYfAxawCSFcAgAqbLYXBSGne9tFyn1gWKwBBFpw5gXOPsQr9UFAo5CFOBGsbhAPCUg6Boc4HFvSVY_ZzjOW8A8b45AdzwmzlQVsTtzckAONVhsyFjbb0ts8eSbAfblXyzWFgahT2mFPKOEdN0Pyd3WmhZMS9yWSnPveQ8n5VgAUgoA4qrF4SDn71OYC0F0gHmRXeYNKgvzyPmgw6AXj0Kiqp1RecXD6I8XcvJfXae0cyGYg82kmTqI2XKfHo3bT-nUlSumXKze6IXWnOPpAs-_r82QHjZ_VNocXVkNzdG15kDykVuK7F6RWDOR4OJQgEh1D6H3ptqw2bbouHtf4cI8R0j0XYAUYEFRoz2M6Nme6MV8QLHbNM4fBxm73Hki7YE6jg76Uc2oPE1aSTjwZOXciUD1CIOvKOPB-p04jOx3CRj7Ad7iBQfflgD9piWmrvpQR-2nHbmA9Pa7KdzHb5_Mudx6n8sE7G9E6iJF3Tc74IU4PUltnhXuD8qY53_dh7e8TgHxe3Z-q-dRGq_QHIdWO0lrE-xEz0L2st4fGYvARFECeKYmyIYUBWoTBgCNCAAB-V3gfSIC7wD14XYFx8DcoENkbIqK8Pm_ZNoUTgawZFmzWKrkBormBvEBBiriKnZtpl7lxttr7qdv7kJh_i1KJqHuHtJrkFHiYlAXisXkjnXmXkgSKjoBjr5vELXoFvXpAQTghCXBvr4NYOCjaAIPjFIBhgbo4CPrqjzrFNPiJKJmqjlqwCIA2r3IgHNC2vru2tYLADaPQiwZ5Owf0KzGpsxhIH2voAOjQU3vxJgBOkAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Creact&prettier=false&targets=&version=7.9.0&externalPlugins=)
